name: CI/CD - Vite React (Docker)

on:
  push:
    branches: ["main"]
    tags: ["v*", "release-*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

env:
  IMAGE_NAME: vite-react-app
  IMAGE_REF: yogevfarjoun/vite-react-app

jobs:
  # ---------- CI (Node: build) ----------
  test-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Tests (optional)
        run: npm test --if-present

      - name: Build Vite
        run: npm run build

      - name: Upload dist (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: ignore

  # ---------- CI (Python: unit tests) ----------
  python-unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Install test requirements
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pytest unittest2
          fi

      - name: Run unit tests (pytest)
        run: python -m pytest --junitxml results.xml tests/*.py

      - name: Upload test report (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: python-tests-junit-${{ github.sha }}
          path: results.xml
          if-no-files-found: warn

  # ---------- CI (Python: lint) ----------
  python-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Install pylint
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pylint
          fi

      - name: Run pylint
        run: |
          set -e
          found_py=$(ls -1 *.py 2>/dev/null | wc -l || true)
          if [ "$found_py" -gt 0 ]; then
            python -m pylint *.py
          fi
          found_tests=$(ls -1 tests/*.py 2>/dev/null | wc -l || true)
          if [ "$found_tests" -gt 0 ]; then
            python -m pylint tests/*.py
          fi

  # ---------- Docker: build & push ----------
  docker:
    runs-on: ubuntu-latest
    needs: [test-and-build, python-unit-tests, python-lint]
    timeout-minutes: 20
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REF }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=long
            type=ref,event=tag
            type=ref,event=branch

      - name: Build & Push image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate build provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.IMAGE_REF }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: false

      - name: Upload provenance (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: provenance-${{ github.sha }}
          path: "**/*.intoto.jsonl"
          if-no-files-found: ignore

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_REF }}@${{ steps.build.outputs.digest }}
          format: spdx-json
          artifact-name: sbom-${{ github.sha }}.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: sbom-*.spdx.json

  # ---------- Security Vulnerability Scanning (Snyk) ----------
  snyk-scan:
    runs-on: ubuntu-latest
    needs: [docker]
    timeout-minutes: 15
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_ORG: ${{ secrets.SNYK_ORG }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk via npm
        run: npm install -g snyk

      - name: Verify SNYK_TOKEN presence (length only)
        run: |
          if [ -z "$SNYK_TOKEN" ]; then
            echo "SNYK_TOKEN is missing"; exit 1
          fi
          echo "SNYK_TOKEN length: $(printf "%s" "$SNYK_TOKEN" | wc -c)"

      - name: Snyk auth
        run: |
          if [ -n "$SNYK_ORG" ]; then
            snyk auth "$SNYK_TOKEN" --org="$SNYK_ORG"
          else
            snyk auth "$SNYK_TOKEN"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull built Docker image
        run: docker pull ${{ env.IMAGE_REF }}:latest

      - name: Snyk container test (high+)
        run: |
          if [ -n "$SNYK_ORG" ]; then
            snyk container test ${{ env.IMAGE_REF }}:latest --file=Dockerfile --severity-threshold=high --org="$SNYK_ORG"
          else
            snyk container test ${{ env.IMAGE_REF }}:latest --file=Dockerfile --severity-threshold=high
          fi

      - name: Snyk JSON report
        continue-on-error: true
        run: |
          if [ -n "$SNYK_ORG" ]; then
            snyk container test ${{ env.IMAGE_REF }}:latest --file=Dockerfile --severity-threshold=high --json --org="$SNYK_ORG" > snyk-report.json
          else
            snyk container test ${{ env.IMAGE_REF }}:latest --file=Dockerfile --severity-threshold=high --json > snyk-report.json
          fi

      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report-${{ github.sha }}
          path: snyk-report.json
          if-no-files-found: ignore
